### ISSUE TITLE
Build args doesn't work

### ISSUE THREAD

**Issue by Fazendaaa** [linuxserver/docker-docker-compose#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I have a scenario similar to the following:

```yaml
version: '3'

services:
    myservice:
        build:
            context: .
            dockerfile: Dockerfile.alpine
            args:
                - MY_VAR=$MY_VAR
```

When I try to run through the recommended docker-compose installation, he can't build because he doesn't find MY_VAR.

## Current Behavior

It says he can't find MY_VAR and ends up leaving it with an 'empty' value, I had to install the docker-compose in order to run the project through the build.

## Environment
**OS:** 5.8.16-2-MANJARO
**CPU architecture:** x86_64
**How docker service was installed:** through the recommended method

## Command used to create docker container (run/create/compose/screenshot)

Behavior presented in both:

```shell
docker-compose up --build
docker-compose build
```
